### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by joshuathompson** [formly-js/angular-formly-website#84]
I'm getting the following when running npm run build:

```
> angular-formly-website@1.0.0 build /Users/joshuathompson/Documents/Projects/angular-formly-website
> NODE_ENV=production webpack --config webpack.config.js --colors --progress

Hash: 396f0bfb9d565b6f60f0  
Version: webpack 1.12.2
Time: 1485ms
    + 1 hidden modules

ERROR in ./app/index.js
Module build failed: Error: "../index.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/joshuathompson/Documents/Projects/angular-formly-website/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at SourceMapGenerator.<anonymous> (/Users/joshuathompson/Documents/Projects/angular-formly-website/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:233:42)
    at Array.forEach (native)
    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/joshuathompson/Documents/Projects/angular-formly-website/node_modules/ng-annotate-loader/node_modules/source-map/lib/source-map/source-map-generator.js:232:34)
    at Object.module.exports (/Users/joshuathompson/Documents/Projects/angular-formly-website/node_modules/ng-annotate-loader/loader.js:20:17)
```

[It looks like there was a similar problem on the Bootstrap-template repo?](https://github.com/formly-js/angular-formly-templates-bootstrap/issues/14)

**Comment by kentcdodds** [comment]
Hmmm... Interesting. That's definitely a different problem. Could you tell me what version of `npm` and `node` you're running as well as your OS?

**Comment by joshuathompson** [comment]
OSX Yosemite
Npm - 2.14.2
Node - v0.12.7

**Comment by joshuathompson** [comment]
I tried updating npm/node, still no luck.  I'm not sure if my process is wrong though because I have never used npm as a task runner.  I just ran npm install and then npm run build.  I have also tried npm start and that gets me to "angular formly is loading..." indefinitely with:

```
Uncaught TypeError: angular.module is not a function - angular-highlightjs.js?./~/imports-loader?hljs=highlight.js:34 
```

**Comment by kentcdodds** [comment]
So yeah, I pulled this down (finally) and I'm getting the same issue. I'm looking into it now.
